### ISSUE TITLE
Support for Plugin Installation in WordPress Playground Theme Preview Action

### ISSUE THREAD

**Issue by erseco** [WordPress/action-wp-playground-pr-preview#45]
First of all, thank you for creating and maintaining the **WordPress Playground Theme Preview Action**! It has proven to be a valuable tool for quickly previewing and testing changes to themes in a dedicated playground environment during pull requests.  

I would like to request the addition of support for installing plugins alongside theme previews. This would greatly enhance the utility of this GitHub Action, especially for those developing plugins or themes that depend on specific plugin behavior or require compatibility checks.

**Proposed Use Cases for Plugin Support:**
- Previewing themes with their required plugins enabled.
- Testing plugin compatibility with a given theme in the playground.
- Plugin development and testing during pull requests to quickly validate changes.

**Proposed Inputs for Plugin Support (Suggestions):**
- `plugins`: A list of plugins (repository URLs, paths, or zip files) to install.
- `plugin-activation`: Boolean input to determine if the plugins should be activated.

**Example Usage:**
```yaml
- name: Preview Theme with Plugins
  uses: vcanales/action-wp-playground-pr-preview@trunk
  with: 
    github-token: ${{ secrets.GITHUB_TOKEN }}
    base-branch: main
    plugins: |
      https://downloads.wordpress.org/plugin/woocommerce.latest-stable.zip
      https://downloads.wordpress.org/plugin/elementor.latest-stable.zip
    plugin-activation: true
```

**Benefits of Adding Plugin Support:**
- Broader testing capabilities for themes that require plugins to function.
- Provides a more comprehensive environment for plugin development testing.
- Allows developers to check theme and plugin compatibility seamlessly within the CI/CD process.

Thank you for considering this feature request! Your continued efforts to make the WordPress ecosystem more efficient and developer-friendly are greatly appreciated.
